name=Vendista
version=1.0.0
author=Zernov <zernovyt@vk.com>
maintainer=Zernov <zernovyt@vk.com>
sentence=API for Vendista vending terminals
paragraph=Control and communication library for Vendista terminals. Allows you to create your own arduino-based Vending Machine Controller. ESP, STM, AVR supported.
category=Device Control
url=https://github.com/zernovtechno/Vendista
architectures=*